### ISSUE TITLE
Could not find a PlexMediaServer-[0-9]*.[0-9]*.[0-9]*.[0-9]*.[0-9]*-[0-9,a-f]*-f reebsd-amd64.tar.bz2 download link on page https://plex.tv/downloads?channel=ple xpass

### ISSUE THREAD

**Issue by ssgoku129** [mstinaff/PMS_Updater#10]
I tried changing the URLs with no luck (because I'm unsure how to correctly change them), been getting the error for about a week now

**Comment by Arcanemagus** [comment]
Almost always this is due to an incorrect PlexPass password, or if you do not have PlexPass you need to specify the `-n` option as Plex has restricted those downloads now (like they were always intended to be).

**Comment by ssgoku129** [comment]
Awesome, thanks! I tried to change my password a week ago but the account page is a little confusing, little did I realize that I didn't change the password at all.
