### ISSUE TITLE
"Command not found" when trying to execute PMS_Updater.sh

### ISSUE THREAD

**Issue by ssgoku129** [mstinaff/PMS_Updater#11]
This is a rather perplexing issue, I thought maybe it had to be related to the file but recreated files made no difference. Here's the output of my shell: http://jamesmorgan.ca/PMS_Updater_shell.png

Any ideas?

**Comment by Arcanemagus** [comment]
Do you have a `/bin/sh`?

**Comment by Arcanemagus** [comment]
Actually that's a FreeNAS jail, it should be there...

**Comment by Arcanemagus** [comment]
If you put a `set -x` on line 2 you should see each command before it executes so you can see what command is failing.

**Comment by ssgoku129** [comment]
Hey so I wasn't totally sure what you meant but it sounds like you wanted me to modify the script and put "set -x" on the blank space in line 2, you can see I did that here, still getting command not found :( http://jamesmorgan.ca/PMS_Updater_shell.png

**Comment by ssgoku129** [comment]
Hey so I wasn't totally sure what you meant but it sounds like you wanted me to modify the script and put "set -x" on the blank space in line 2, you can see I did that here, still getting command not found :( http://jamesmorgan.ca/pmsfail.png

**Comment by ssgoku129** [comment]
Hey I was just curious what would happen if I ran the command from the root of my FreeNAS shell, this is the error I get when I try http://jamesmorgan.ca/freenasroot.png

**Comment by ssgoku129** [comment]
http://jamesmorgan.ca/maybethis.png just kind of googling around, hope you don't mind the spam messaging, but this looked interesting, "Check whether your script or data has DOS style end-of-line characters"

**Comment by Arcanemagus** [comment]
You need to run the script from within the jail, it would need a _lot_ of modification to work outside of it.

If you have CRLF line endings that should be fixed, you could always clone it from within the jail :wink:.

**Comment by ssgoku129** [comment]
Sorry for the confusion but I tried running the script from outside of the jail merely as a test, if you'd like to see a screenshot of it in the jail, here you go: http://jamesmorgan.ca/pmsfail.png

**Comment by ssgoku129** [comment]
when you say clone it, do you mean to run: git clone https://github.com/mstinaff/PMS_Updater.git ?

**Comment by Arcanemagus** [comment]
Exactly, that should give you a guaranteed good version.

**Comment by ssgoku129** [comment]
I never used git before, had to install it with pkg first but yayyy, thanks @Arcanemagus, that worked perfectly... now I'm curious why I can't just make a blank file and fill code with notepad anymore, I mean, your way is better but I am curious what the issue might have been that these unfriendly DOS characters are showing up :(

**Comment by Arcanemagus** [comment]
Well, using Notepad for starters :stuck_out_tongue:, I'm assuming you created the file on a windows machine and then moved it into the jail. You can still do that but you need to use a smarter text editor that understands line endings like Atom or Notepad++.

**Comment by ssgoku129** [comment]
that's what surprising me, I'm using Notepad++ :( I'll give Atom a try!

**Comment by Arcanemagus** [comment]
If you are using Notepad++ you just need to make sure you are using the correct line ending (Edit -> EOL Conversion -> UNIX/OSX Format). Atom is an awesome editor though so you should check it out anyway :wink:.
