### ISSUE TITLE
downloads just fine but doesn't update

### ISSUE THREAD

**Issue by ovizii** [mstinaff/PMS_Updater#13]
I ran PMS_updater.sh with the -v flag and was asked twice for my password: 

`HTTP request sent, awaiting response... 200 OK
Length: 97567280 (93M) [application/octet-stream]
Saving to: '/tmp/PlexMediaServer-0.9.16.3.1840-cece46d-freebsd-amd64.tar.bz2'

PlexMediaServer-0.9.16.3.1840-cece46d-freebsd 100%[================================================================================================>]  93.05M  2.92MB/s   in 30s

2016-03-29 20:26:16 (3.08 MB/s) - '/tmp/PlexMediaServer-0.9.16.3.1840-cece46d-freebsd-amd64.tar.bz2' saved [97567280/97567280]

Download Complete`

and then I'm back to my shell so it downloads and then does nothing !?! huh? Any ideas?

**Comment by Arcanemagus** [comment]
You didn't tell it to actually run the update (`-a`), by default this script (correctly!) does nothing that might break your installation unless you explicitly tell it to.

**Comment by ovizii** [comment]
*sigh* I must have had a blonde moment :-( 

read the script 3 times, tried passing my credentials via command line, password file, tried downloading then using a local fiel with the "-l" switch, basically did everything but use the "-a" switch. 

Sorry for the noise
