### ISSUE TITLE
Plex crashed and no more updates :(

### ISSUE THREAD

**Issue by vincegre** [mstinaff/PMS_Updater#14]
Hi

This morning I have a strange problem. I found my PMS stopped on my FreeNAS. I try to restart it from freeNAS web gui but it doesn't. I restarted FreeNAS but still the same.
I ran by hand the script that goes well but still doesn't update with new release of this night !
I made -f to force update with current version and I got that: (replaced login/pass for confidentiality)

```
[root@FREENAS ~]# jexec plexmediaserver_1 ./PMS_Updater.sh -u YYYYYY -p XXXXXXXX -a -f                                
Done.                                                                                                                               
Done                                                                                                                                
Done.                                                                                                                               
Done.                                                                                                                               
Done.                                                                                                                               
Done.                                                                                                                               
Starting plexmediaserver.                                                                                                           
Done.                                                                                                                               
[root@FREENAS ~]
```

But Plex is still not running :(

Any ideas what I can check to find the issue ?

Thanks

**Comment by derblub** [comment]
Check your logs. Just had exactly the same issues and resolved it by changing the owner and group of `/plexdata/`  

The error in my log was:  
```
 ERROR - FATAL ERROR: Codecs: Initialize: 'boost::filesystem::create_directories: Permission denied: "/var/db/plexdata/Plex/Codecs"'
```

**Comment by jasongi** [comment]
> Check your logs. Just had exactly the same issues and resolved it by changing the owner and group of /plexdata/

+1 for this, I solved the problem with the following command
`chown -R plex:plex /var/db/plexdata/`

**Comment by vincegre** [comment]
Yep found that also with log, changed rights on directory and back to work now :)
