### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by GJean** [mstinaff/PMS_Updater#15]
I try to update with plex media server 1.0 but I have this error : 
`--2016-06-24 08:18:02--  https://plex.tv/downloads?channel=plexpass  
Resolving plex.tv (plex.tv)... 52.17.109.161, 52.19.111.38, 54.76.231.216, ...  
Connecting to plex.tv (plex.tv)|52.17.109.161|:443... connected.  
HTTP request sent, awaiting response... 404 Not Found  
2016-06-24 08:18:12 ERROR 404: Not Found.                                       

Error downloading https://plex.tv/downloads?channel=plexpass`

**Comment by itbrl99** [comment]
I can confirm, same issue here!

**Comment by UnR34L** [comment]
I think it's using a outdated link now. I got it working with the '-l' switch, like this:

./PMS_Updater.sh -f -v -l ./PlexMediaServer-1.0.0.2261-a17e99e-freebsd-amd64.tar.bz2

It's not ideal but it's still the easiest way to install.

**Comment by ivanpedersen** [comment]
+1 here for the same issue... :(

**Comment by dxm765** [comment]
Same issue, the above trick will work just isnt a permanent fix.

**Comment by mneumark** [comment]
Same issue here. Resolved it the same way.

**Comment by Naesstrom** [comment]
Yup, same problem here! Looks like it's because they've changed the homepage for the 1.0 version!

**Comment by mneumark** [comment]
Also just noting that the new version of the site provides the following URL which will be very helpful....
```
https://plex.tv/api/downloads/1.json?channel=plexpass
```

**Comment by mneumark** [comment]
Further more, FreeBSD's `pkg` installer has `jq`, which allows the following:
`curl -s https://plex.tv/api/downloads/1.json?channel=plexpass 2>&1 | jq 'getpath(["computer", "FreeBSD", "releases", 0, "url"])'`

Might put in a PR, if I submitted a PR that mandated installing `jq` would that dependency bother anyone?

**Comment by mneumark** [comment]
@tedrock Just to be certain, did you go to Plex's site and actually download that file first?

**Comment by Naesstrom** [comment]
@tedrock you need to download the file manually first and put it next to the PMS_Updater.sh script!

**Comment by tedrock** [comment]
Nope, that would explain a lot, thanks guys.

**Comment by mneumark** [comment]
Okay, Put in a pull request here to fix the problem:
https://github.com/mstinaff/PMS_Updater/pull/16

**Comment by mstinaff** [comment]
Still here. Should be at my computer tonight and can review and pull then.

**Comment by mneumark** [comment]
My PR just got merged so go ahead and grab the new copy and try again.

**Comment by mstinaff** [comment]
Hmmm. Just tried and it is saying that I am already running the current version 0.9.17....
Then again I am squinting at an SSH session on my phone.  So maybe I try again when I get home

**Comment by GJean** [comment]
thanks, it's work for me.

**Comment by dxm765** [comment]
I just tried and it returned "Done." very quickly, way too quickly. And shows I'm still on 0.9.16.6.

**Comment by UnR34L** [comment]
Already on the newest version but returning no errors. seems to be fixed.

**Comment by vincegre** [comment]
Same as dxm765 :( replaced my script with new one and now it just says ok (very quickly) and nothing happens, still stuck in version 0.9 (FreeNAS 9.3 here !)

**Comment by mstinaff** [comment]
Dxm765. Vincegre does the latest version of the script work for you?

**Comment by vincegre** [comment]
mstinaff nope sorry I didn't mention it in my post but I updated first the script with latest version released yesterday but it doesn't work ! Just tells Done one time and nothing else and PMS not updated !

**Comment by mstinaff** [comment]
What output do you get it you pass -v ?

**Comment by dxm765** [comment]
Negative, I now get:

"./PMS_Updater.sh: --version: not found
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
./PMS_Updater.sh: https://plex.tv/api/downloads/1.json?channel=plexpass: not found
Error downloading https://plex.tv/api/downloads/1.json?channel=plexpass        
"

**Comment by mneumark** [comment]
-v is verbose. Not version. Can you literally do `-v`. Sorry I've been gone after submitting that pr. Went out of town. Also hard to test when I already updated to 1.0.0 myself...

**Comment by mneumark** [comment]
What happens when you say:
`ls -la /usr/pbi/plexmediaserver-amd64/share/plexmediaserver`

The --version is actually being sent to `/usr/pbi/plexmediaserver-amd64/share/plexmediaserverPlex\ Media\ Server --version`

Not sure why it can't find that path but it certainly can't find your Plex Server binary.

**Comment by JkJ076** [comment]
I have this issue...

Download Complete                                                                                                                   
Verifying /tmp/PlexMediaServer-1.15.2.793-782228f99-FreeBSD-amd64.tar.bz2 .....Done                                                 
Removing previous PMS Backup .....Done.                                                                                             
Stopping Plex Media Server .....plexmediaserver_plexpass does not exist in /etc/rc.d or the local startup                           
directories (/usr/local/etc/rc.d), or is not executable                                                                             
Done.                                                                                                                               
Moving current Plex Media Server to backup location .....Done.                                                                      
Extracting /tmp/PlexMediaServer-1.15.2.793-782228f99-FreeBSD-amd64.tar.bz2 .....Done.                                               
Starting Plex Media Server .....plexmediaserver_plexpass does not exist in /etc/rc.d or the local startup                           
directories (/usr/local/etc/rc.d), or is not executable                                                                             
Done.
