### ISSUE TITLE
./PMS_Update.sh results in newline unexpected?

### ISSUE THREAD

**Issue by bonmots** [mstinaff/PMS_Updater#17]
Trying to execute the following:
# ./PMS_Update.sh -a

Results in: 

./PMS_Update.sh: 5: Syntax error: newline unexpected

Am I doing this incorrectly? I had already did a chmod 775

**Comment by dxm765** [comment]
Had the same, until i remade the script in nano on my Plex Plugin. After doing so it just returns "Done." instead of actually updating.

**Comment by mstinaff** [comment]
Is this working with the latest version of the script?

**Comment by CharlesSaint007** [comment]
> Trying to execute the following:
>
> ./PMS_Update.sh -a
>
> Results in:
>
> ./PMS_Update.sh: 5: Syntax error: newline unexpected
>
> Am I doing this incorrectly? I had already did a chmod 775

Bonmots, I believe the problem is that you used fetched

https://github.com/mstinaff/PMS_Updater/blob/master/PMS_Updater.sh

Instead of fetching the following:

`fetch -o PMS_Updater.sh https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh`

Try navigating to the current location of your PMS updater script, then running the above lines. That should fix your issue.

**Comment by krin-san** [comment]
Git the same issue today because tried to download script from `https://github.com/mstinaff/PMS_Updater/blob/master/PMS_Updater.sh` url so HTML page was downloaded instead of a raw script =)

Maybe a "How to Use?" section in project README file could help with such mistakes?

**Comment by visseroth** [comment]
Currently getting...
Using URL https://plex.tv/api/downloads/5.json?channel=plexpass
Downloading https://plex.tv/api/downloads/5.json?channel=plexpass
--2019-04-03 20:39:55--  https://plex.tv/api/downloads/5.json?channel=plexpass
Resolving plex.tv (plex.tv)... 54.154.198.3, 63.32.177.143, 52.31.211.151, ...
Connecting to plex.tv (plex.tv)|54.154.198.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘/tmp/5.json?channel=plexpass’

5.json?channel=plexpass                                         [ <=>                                                                                                                                     ]  17.47K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2019-04-03 20:39:56 (129 MB/s) - ‘/tmp/5.json?channel=plexpass’ saved [17891]

Download Complete
Searching https://plex.tv/api/downloads/5.json?channel=plexpass for the FreeBSD download URL ....../PMS_Updater.sh: perl: not found
Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.json?channel=plexpass
