### ISSUE TITLE
00009334581725100040007: out of range          

### ISSUE THREAD

**Issue by ssgoku129** [mstinaff/PMS_Updater#19]
I'm getting the following output from my FreeNAS root (get the same from running the update from the jail):

[root@freenas ~]# jexec 1 /PMS_Updater/PMS_Updater.sh -r -u ssgoku129 -p derpieiderp                                                                           
[: 00009334581725100040007: out of range
Done.

*Note: That's not my real password

**Comment by tedrock** [comment]
Just curious... What happens when you run it with -v (verbose)? I get the same error plus two more out of ranges:
```
[: 11300024083266610000: out of range  
[: 14132776000400010002: out of range
[: 00009334581725100040007: out of range
```
But in verbose mode it shows it's working and doesn't give the errors.

**Comment by ssgoku129** [comment]
@tedrock looks like it's working too :) but still get that out of range error half-way through:

Removing .ICE-unix                                                                                                                  
Removing .XIM-unix                                                                                                                  
Removing .font-unix                                                                                                                 
Removing PMS_Updater.log                                                                                                            
Removing PlexMediaServer-0.9.15.4.1679-e4df231-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.15.5.1712-ba5070a-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.15.6.1714-7be11e1-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.0.1754-23623fb-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.1.1794-af21b7e-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.2.1827-df572f6-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.3.1840-cece46d-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.4.1911-ee6e505-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.5.1966-81a3bf0-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.6.1993-5089475-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.17.2.2159-2bd156c-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.17.3.2239-fe07491-freebsd-amd64.tar.bz2                                                                
[: 00009334581725100040007: out of range                                                                                            
Removing downloads?channel=plexpass                                                                                                 
Using URL https://plex.tv/api/downloads/1.json?channel=plexpass                                                                     
Downloading https://plex.tv/api/downloads/1.json?channel=plexpass                                                                   
--2016-06-29 08:58:40--  https://plex.tv/api/downloads/1.json?channel=plexpass                                                      
Resolving plex.tv (plex.tv)... 52.19.111.38, 54.76.231.216, 52.48.112.19, ...                                                       
Connecting to plex.tv (plex.tv)|52.19.111.38|:443... connected.                                                                     
HTTP request sent, awaiting response... 200 OK                                                                                      
Length: unspecified [application/json]                                                                                              
Last-modified header missing -- time-stamps turned off.                                                                             
--2016-06-29 08:58:41--  https://plex.tv/api/downloads/1.json?channel=plexpass                                                      
Reusing existing connection to plex.tv:443.                                                                                         
HTTP request sent, awaiting response... 200 OK                                                                                      
Length: unspecified [application/json]                                                                                              
Saving to: ‘/tmp/1.json?channel=plexpass’                                                                                           
                                                                                                                                    
1.json?channel=plexpass              [ <=>                                                         ]  18.40K  --.-KB/s   in 0s      
                                                                                                                                    
2016-06-29 08:58:41 (170 MB/s) - ‘/tmp/1.json?channel=plexpass’ saved [18839]                                                       
                                                                                                                                    
Download Complete                                                                                                                   
Searching https://plex.tv/api/downloads/1.json?channel=plexpass for the FreeBSD download URL .....Done.                             
Already running latest version v1.0.0.2261-a17e99e

**Comment by tedrock** [comment]
`Removing .ICE-unix                                                                                                                  
Removing .XIM-unix                                                                                                                  
Removing .font-unix                                                                                                                 
[: 11300024083266610000: out of range                                                                                               
[: 14132776000400010002: out of range                                                                                               
Removing PMS_Updater.log                                                                                                            
Removing PlexMediaServer-0.9.12.19.1537-f38ac80-freebsd-amd64.tar.bz2                                                               
Removing PlexMediaServer-0.9.14.3.1555-590ac74-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.15.0.1621-344f193-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.15.1.1639-26325ea-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.3.1840-cece46d-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.4.1911-ee6e505-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.16.6.1993-5089475-freebsd-amd64.tar.bz2                                                                
Removing PlexMediaServer-0.9.17.2.2159-2bd156c-freebsd-amd64.tar.bz2                                                                
[: 00009334581725100040007: out of range                                                                                            
Removing a0c3-e38e-0b75-1273.srt                                                                                                    
Removing c0f2-af36-5d32-b90c.srt                                                                                                    
Removing downloads                                                                                                                  
Removing downloads?channel=plexpass                                                                                                 
Removing periodic.0DhLDpEVaa                                                                                                        
Removing periodic.KM1OOVoolC                                                                                                        
Removing periodic.QbMkSvOzbA                                                                                                        
Removing periodic.iLGNjcxqQa                                                                                                        
Removing security.uVVd1krP                                                                                                          
Using URL https://plex.tv/api/downloads/1.json?channel=plexpass                                                                     
Downloading https://plex.tv/api/downloads/1.json?channel=plexpass                                                                   
--2016-06-29 13:36:51--  https://plex.tv/api/downloads/1.json?channel=plexpass                                                      
Resolving plex.tv (plex.tv)... 52.19.111.38, 54.76.231.216, 52.17.109.161, ...                                                      
Connecting to plex.tv (plex.tv)|52.19.111.38|:443... connected.                                                                     
HTTP request sent, awaiting response... 200 OK                                                                                      
Length: unspecified [application/json]                                                                                              
Last-modified header missing -- time-stamps turned off.                                                                             
--2016-06-29 13:36:52--  https://plex.tv/api/downloads/1.json?channel=plexpass                                                      
Reusing existing connection to plex.tv:443.                                                                                         
HTTP request sent, awaiting response... 200 OK                                                                                      
Length: 18839 (18K) [application/json]                                                                                              
Saving to: ‘/tmp/1.json?channel=plexpass’                                                                                           
                                                                                                                                    
100%[==========================================================================================>] 18,839      --.-K/s   in 0s       
                                                                                                                                    
2016-06-29 13:36:52 (86.9 MB/s) - ‘/tmp/1.json?channel=plexpass’ saved [18839/18839]                                                
                                                                                                                                    
Download Complete                                                                                                                   
Searching https://plex.tv/api/downloads/1.json?channel=plexpass for the FreeBSD download URL .....Done.                             
Already running latest version v1.0.0.2261-a17e99e`

same thing. Also it's weird it keeps trying to delete past versions... Shouldn't they be deleted after the first try?

**Comment by tedrock** [comment]
I "fixed it"/found out the cause. I deleted everything in /tmp and I don't get the error. Looks like it's having some issue deleting files in there.

**Comment by ssgoku129** [comment]
@tedrock excellent! Issue is gone, I guess I'll close this now? Thanks for determining that so quickly :)
