### ISSUE TITLE
PMS_Updater.sh does not see the latest update

### ISSUE THREAD

**Issue by durrillj** [mstinaff/PMS_Updater#20]
when running the following:
`./PMS_Updater.sh -v -a -c plex_pass`

it returns:
```
Download Complete
Searching https://plex.tv/api/downloads/1.json?channel=plexpass for the FreeBSD download URL .....Done.
Already running latest version v1.0.0.2261-a17e99e
```

The issue is that the current latest version is v1.0.2.2413-7caf41d

**Comment by tbville** [comment]
Get the latest version of the updater with the following after you are the folder with the pas_updater.sh file

fetch --no-verify-peer -o PMS_Updater.sh https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh

this will get the latest then you will be able to update plex server, I was just able to update.
