### ISSUE TITLE
-l argument not working :(

### ISSUE THREAD

**Issue by vincegre** [mstinaff/PMS_Updater#21]
Hi

Following the preview released by Plex with new DVR function, I downloaded it (it's only avalaible from forums) and wanted to install it by doing a:

> ./PMS_Updater.sh -l PlexMediaServer-1.2.0.2716-837790c-freebsd-amd64.tar.bz2

but it does nothing, it immediately comes back to shell !

Any ideas ?

Thanks

Vincèn

**Comment by vincegre** [comment]
Sorry you can close that opened issue ;) Have realised it needed -a flag also to do the update !

**Comment by thesymbol** [comment]
you can close the issue yourself aswell instead of waiting for the repo owner

**Comment by vincegre** [comment]
Thanks, didn't notice I could do it myself :(

**Comment by thesymbol** [comment]
no problem, :+1:
