### ISSUE TITLE
Unusual daily signal 11 segfault after running PMS_Updater

### ISSUE THREAD

**Issue by mhors** [mstinaff/PMS_Updater#22]
However, since I ran the PMS_Updater script I do get the following warning in my daily Freenas security run:

"pid 12629 (Plex Media Scanner), uid 972: exited on signal 11"

The pid number changes each day.

The PMS_updater script seems to have worked fine on my Freenas box. I can access Plex and play media. I can also scan my media.

I run FreeNAS-9.10.1-U4 (ec9a7d3) on a HP N40L server. PMS was updated to 1.2.7.2987.

I used [ceos3c's step by step](https://www.ceos3c.com/2016/08/27/freenas-series-2-manually-updating-plex-media-server/#more-95):

1. Connect to your Freenas via SSH or open the Shell via Web GUI
2. Type: jls and note the # of your Plex Media Server jail
3. Type: jexec #jailnumber csh (for example: jexec 1 csh)
4. Type: fetch -o PMS_Updater.sh https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh
5. Type: chmod 755 PMS_Updater.sh
6. Type: ./PMS_Updater.sh -vv -a

It may not be related to the PMS update, but I read that signal 11 is a segfault that ought to be looked into.

"A segmentation fault occurs when a program attempts to access a memory location that it is not allowed to access, or attempts to access a memory location in a way that is not allowed (for example, attempting to write to a read-only location, or to overwrite part of the operating system)."

Is this related to the PMS_Updater or should I look elsewhere?

**Comment by Arcanemagus** [comment]
Recent versions of the Media Scanner seem to exit with that _very_ often, this has nothing to do with the script though as I get is using the `pkg` archive.

**Comment by mhors** [comment]
Thanks. I'll raise this with the PMS forum. Must be a later version of PMS.

Marcel

**Comment by Arcanemagus** [comment]
Looks like there is http://forums.plex.tv/discussion/245663/plex-media-scanner-exited-on-signal-11, I'll add the information I have to that thread.

**Comment by mhors** [comment]
Thanks Landon,

Not spotted this forum message.

Will try the Monit solution. Seems a PMS bug. Much appreciated.

Marcel

**Comment by mhors** [comment]
One more point. In Freenas, the PMS jail is recorded as "Plexmediaserver	1.1.4.2757	plexmediaserver-1.1.4.2757-amd64	plexmediaserver_1" where in PMS it shows the correctly updated version of "Version 1.2.7.2987"

FreeNAS gives the option to update PMS, but when I do, it downloads, but then hangs at 50%. Rebooted Freenas, but still same old version recorded in Freenas UI.

Looked into using Monit to restart PMS from above link, but as PMS is running fine without crashes, this is not really needed,

Am I best to ignore PMS updates and version numbers in Freenas?

**Comment by Arcanemagus** [comment]
If you are using the Plex plugin jail from FreeNAS I'm not entirely sure what updating that entails. I run Plex from a custom jail myself...

Since the important part is Plex itself, you can probably ignore that, although you are likely missing out on OS updates to the jail.

**Comment by xmicks** [comment]
I read on the Freenas forums that, only when you update through the UI the version there is updated. When you update manually, your plugin is updated, but the version number is not in the UI.

**Comment by ssgoku129** [comment]
The UI is not reporting a version, it's just a package name, it doesn't look through your plex install to determine what version it's running, this goes for all of the packages on FreeNAS. It's better to run Plex through a custom jail and use PMS_Updater to get the latest PlexPass updates which the FreeNAS plugin does not look for.
