### ISSUE TITLE
Script tells me I'm on the latest version and I'm not

### ISSUE THREAD

**Issue by Wolfeman0101** [mstinaff/PMS_Updater#23]
v1.5.0.3501 is available but using the script I get this.

```
Using URL https://plex.tv/api/downloads/1.json?channel=plexpass
Downloading https://plex.tv/api/downloads/1.json?channel=plexpass
--2017-03-19 20:20:32--  https://plex.tv/api/downloads/1.json?channel=plexpass
Resolving plex.tv (plex.tv)... 52.17.240.145, 54.229.174.245, 52.210.15.168, ...
Connecting to plex.tv (plex.tv)|52.17.240.145|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24586 (24K) [application/json]
Saving to: '/tmp/1.json?channel=plexpass'

1.json?channel=plexpass      100%[============================================>]  24.01K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2017-03-19 20:20:33 (155 MB/s) - '/tmp/1.json?channel=plexpass' saved [24586/24586]

Download Complete
Searching https://plex.tv/api/downloads/1.json?channel=plexpass for the FreeBSD download URL .....Done.
Already running latest version v1.4.4.3495-edef59192
```

If you go to the URL you can see there is the 1.5 version available https://plex.tv/api/downloads/1.json?channel=plexpass

**Comment by SethWilliamson** [comment]
Same issue.

Work-around until fixed: Manually download update, then run:
./PMS_Updater.sh -f -v -l ./PlexMediaServer-[...].bz2

**Comment by WillieWookiee** [comment]
I believe that I am having the same problem. Seems to be related to the authentication passthrough for wget when it downloads from the API URL. I am working to see if I can resolve this.

**Comment by t3hG04T** [comment]
I only see 1.4.4 in the JSON (both manualy and via the script). Web GUI doesn't seem to be reporting an update available either.

**Comment by WillieWookiee** [comment]
t3hG04T, that's because you aren't signed in with PlexPass. That is the problem. If you have plexpass, you can sign in through the website, then view that downloads URL and it will show 1.50. That version is only available to Plexpass members right now.

**Comment by t3hG04T** [comment]
Ah, that must be it then, true.

**Comment by WillieWookiee** [comment]
Now I feel like a moron. I was using the wrong password, but I will say if you use the info file that includes the username and password, leave out the "{}".

**Comment by SethWilliamson** [comment]
@WillieWookiee You got it to pull the latest version? I agree that it appears to be an authentication issue, however, I've had mine working successfully via a cron job for a while now, but it failed with this latest update. This led me to wonder if Plex changed something server-side which broke the script. 

I'll have to wait until the next update to troubleshoot further, since I manually updated to 1.5.0.

**Comment by WillieWookiee** [comment]
Yes, I got it to pull 1.5 via PlexPass using a credential file with my username and password. I even manually ran the wget command it uses to pull the download link and it pulled 1.50 URLs.

**Comment by Wolfeman0101** [comment]
It's like it's cached or something and after a few days it will pull the right version.

**Comment by SethWilliamson** [comment]
Lucky me, there's another update. This time my cron job updated successfully. You might be on to something about caching.

**Comment by Wolfeman0101** [comment]
I'm having the same issues still.

`Using URL https://plex.tv/api/downloads/1.json?channel=plexpass
Downloading https://plex.tv/api/downloads/1.json?channel=plexpass
--2017-03-24 18:28:47--  https://plex.tv/api/downloads/1.json?channel=plexpass
Resolving plex.tv (plex.tv)... 54.229.174.245, 54.77.213.127, 52.214.149.31, ...
Connecting to plex.tv (plex.tv)|54.229.174.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24586 (24K) [application/json]
Saving to: '/tmp/1.json?channel=plexpass'

1.json?channel=plexpass      100%[============================================>]  24.01K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2017-03-24 18:28:48 (207 MB/s) - '/tmp/1.json?channel=plexpass' saved [24586/24586]

Download Complete
Searching https://plex.tv/api/downloads/1.json?channel=plexpass for the FreeBSD download URL .....Done.
Already running latest version v1.5.0.3501-3b8374a5c
root@plexmediaserver_1:/ #
`

**Comment by WillieWookiee** [comment]
@Wolfeman0101, What is the command you are using to run the update via cron?

Also, can you validate your user creds?

**Comment by Wolfeman0101** [comment]
PMS_Updater.sh -u email@gmail.com -p password -v -a

**Comment by jflatz** [comment]
I too had this issue but after several attempts of running the script and restarts of PMS I was able to get it to update to the newest version.

**Comment by angyp** [comment]
This seems to be a problem again. I am on 1.14.1.5488 Plex GUI states 1.15.0.659 is available but get I get this when running the script

Using URL https://plex.tv/api/downloads/1.json?channel=plexpass
Downloading https://plex.tv/api/downloads/1.json?channel=plexpass
--2019-02-08 11:30:21--  https://plex.tv/api/downloads/1.json?channel=plexpass
Resolving plex.tv (plex.tv)... 52.16.101.236, 63.32.24.1, 54.76.255.232, ...
Connecting to plex.tv (plex.tv)|52.16.101.236|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘/tmp/1.json?channel=plexpass’

1.json?channel=plex     [ <=>                ]  29.99K  --.-KB/s    in 0.001s

Last-modified header missing -- time-stamps turned off.
2019-02-08 11:30:23 (34.6 MB/s) - ‘/tmp/1.json?channel=plexpass’ saved [30710]

Download Complete
Searching https://plex.tv/api/downloads/1.json?channel=plexpass for the FreeBSD download URL .....Done.
Already running latest version v1.14.1.5488-cc260c476

**Comment by ErebusBat** [comment]
@angyp,

`v1.14.1.5488-cc260c476` appears to be correct for the _stable_ channel.

It sounds like you have PMS_Updater checking the stable channel, but the UI set on the beta channel.

**Comment by ravensorb** [comment]
How do you set PMS_Updater to check the beta channel?
