### ISSUE TITLE
No Match Error

### ISSUE THREAD

**Issue by carl20236** [mstinaff/PMS_Updater#28]
Trying to update the server manually.  Have the instructions and entered them, but continually getting a "No Match" message.  I've typed in the username and password correctly.  Any thoughts???  Thanks.

**Comment by statik1983** [comment]
Download the latest version again. 

fetch -o PMS_Updater.sh https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh

chmod 777 PMS_Updater.sh

./PMS_Updater.sh -u [your plexpas email address] -a -v

**Comment by afettouhi** [comment]
Having the same issue as well. Tried today to update plexpass manually and I keep getting that error.
