### ISSUE TITLE
Add support for upgrade ta plex 1.15.x

### ISSUE THREAD

**Issue by programmerq** [mstinaff/PMS_Updater#29]
I noticed that my server had a new version notification but PMS_Update.sh wasn't picking up the new version. After some digging I found the following information: https://forums.plex.tv/t/linux-download-link-is-still-for-1-14/372535/59

Summarized the relevant parts here for readability and posterity in case anything happens to that forum thread.

> **WingmanNZ** • _Plex Employee_ •  2019 Feb 11, 9:54 PM
> We are still working on a fix required for our website that talks to the downloads API (the json endpoint)
> 
> In the mean time, if you have scripts that look for plexpass downloads via https://plex.tv/api/downloads/1.json?channel=plexpass you can simply use https://plex.tv/api/downloads/5.json?channel=plexpass instead. (be sure to provide your Plex Token in the header for the request, or as a parameter in the request)

...

> **WingmanNZ** • _Plex Employee_ • 2019 Feb 11, 10:30 PM
> `1.json` is the old CI/build system (PMS 1.14.1 and older), `5.json` is the new CI/build system (1.15.0 and newer)

Basically, the URL in PMS_Update.sh should be changed to 5.json. The change could happen any time starting now.

**Comment by angyp** [comment]
Updating the script to 5.json will work and the script will download and install 1.15. But looks like a few extra changes are going to be needed to get 1.15 to run correctly. 
https://forums.plex.tv/t/pms-1-15-0-659-settings-unavailable-and-playback-broken/376194

**Comment by SaskiFX** [comment]
Yea, it looks like just unpacking the new download won't work anymore. I had to go back a version to get things playing again.

https://forums.plex.tv/t/pms-1-15-0-659-settings-unavailable-and-playback-broken/376194/7
