### ISSUE TITLE
Cannot find release file.

### ISSUE THREAD

**Issue by nx6** [mstinaff/PMS_Updater#32]
Currently on PMS version 1.14.0.5470

I've used your scripts several times to update Plex on my FreeNAS, but I seem to be unable to now. The script indicates it can't find the file for the current stable (non-Plex Pass) release. Not sure if this is a case of Plex relocating the file in the path your script uses?

root@plexmediaserver_1:/ # ./PMS_Updater.sh -n -v -a                            
Using URL https://plex.tv/api/downloads/5.json                                  
Downloading https://plex.tv/api/downloads/5.json                                
--2019-02-23 02:51:25--  https://plex.tv/api/downloads/5.json                   
Resolving plex.tv (plex.tv)... 52.18.254.79, 54.171.147.115, 52.16.101.236, ... 
Connecting to plex.tv (plex.tv)|52.18.254.79|:443... connected.                 
HTTP request sent, awaiting response... 200 OK                                  
Length: unspecified [application/json]                                          
Last-modified header missing -- time-stamps turned off.                         
--2019-02-23 02:51:26--  https://plex.tv/api/downloads/5.json                   
Reusing existing connection to plex.tv:443.                                     
HTTP request sent, awaiting response... 200 OK                                  
Length: unspecified [application/json]                                          
Saving to: ‘/tmp/5.json’                                                        
                                                                                
    [ <=>                                   ] 24          --.-K/s   in 0s       
                                                                                
2019-02-23 02:51:26 (1.01 MB/s) - ‘/tmp/5.json’ saved [24]                      
                                                                                
Download Complete                                                               
Searching https://plex.tv/api/downloads/5.json for the FreeBSD download URL ....
.Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.
json                                            

The current version is [certainly available](https://downloads.plex.tv/plex-media-server/1.14.1.5488-cc260c476/PlexMediaServer-1.14.1.5488-cc260c476-freebsd-amd64.tar.bz2) on the normal download site.

**Comment by statik1983** [comment]
I was having the same problem.  You need to download his latest PMS_Updater.sh that he just recently updated.

**Comment by statik1983** [comment]
fetch -o PMS_Updater.sh https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh

chmod 777 PMS_Updater.sh

./PMS_Updater.sh -u [your plexpas email address] -a -v

**Comment by statik1983** [comment]
Hold on doing that... Now plex is not starting for me....

**Comment by nx6** [comment]
I was going to say, I download a fresh copy of the script whenever I run an update.
Also, changing permissions to 755 is enough.

**Comment by statik1983** [comment]
I had to download and install the 1.14 version to get it working again.  

./PMS_Updater.sh -l PlexMediaServer-1.14.1.5488-cc260c476-freebsd-amd64.tar.bz2 -v -a -f

are you having the same issue with Plex not starting after updating to 1.15?

**Comment by nx6** [comment]
I'm not updating to 1.15. I'd rather wait for them to iron out the bugs with the new build system.
I'm just trying to update to the current /stable/ release, from December.

Note: I should also mention I'm on FreeNAS 9.2.1.9 still.

**Comment by statik1983** [comment]
I see.  why not update your freenas to 11.1 ?  I think the new script is the issue.  I just ran the new script with the same commands ./PMS_Updater.sh -n -v -a that you used and get the same result.
