### ISSUE TITLE
Should we push an update to rc.d to fix it for the new updates?

### ISSUE THREAD

**Issue by StarkITA** [mstinaff/PMS_Updater#34]
Referencing #33 and [this](https://forums.plex.tv/t/i-updated-to-plexmediaserver-1-15-0-659-9311f93fd-and-now-i-cant-access-server-setting/377180/14), should we add something to OVERWRITE (of course with user permission) rc.d to make it work for the new updates?

**Comment by StarkITA** [comment]
There are still issues, and the plex devs are still providing a solution.

**Comment by Rewur** [comment]
that would be great because I have no idea what to do

**Comment by BreakBert** [comment]
that will be really cool! like Rewur i have also no idea what to do with the error

**Comment by jbeez** [comment]
Is this still an issue? What is going on with it?
