### ISSUE TITLE
After update getting "Server settings are unavailable."

### ISSUE THREAD

**Issue by visseroth** [mstinaff/PMS_Updater#37]
After running update getting ... "Server settings are unavailable."

**Comment by terzano** [comment]
Confirmed, I am experiencing the same issue w/ FreeNAS 11.2U3. Plex installed using native iocage as Plugin.

**Comment by jasonbuechler** [comment]
@visseroth and @terzano 
I have a couple forum posts on fixing this:

- https://forums.plex.tv/t/i-updated-to-plexmediaserver-1-15-0-659-9311f93fd-and-now-i-cant-access-server-setting/377180/94?u=jasonbuechler
- https://www.ixsystems.com/community/threads/cant-update-plex-on-freenas-11-2.72133/page-3#post-503553

It's not very complicated. But feel free to hit me up here if you need any assistance.

@mstinaff I wouldn't mind at all contributing to your script if you wanted/needed any extra help

**Comment by visseroth** [comment]
@jasonbuechler Thanks, I just saw your message, I'll give it a go as soon as I have a few minutes to test.
