### ISSUE TITLE
script can't find plex install or perl?

### ISSUE THREAD

**Issue by tfbiii** [mstinaff/PMS_Updater#39]
FreeNAS vFreeNAS-11.2-U3
Clean install of Plex-PlexPass plugin.

I get the following errors when trying to run the script:

./PMS_Updater.sh: /usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Plex Media Server: not found
./PMS_Updater.sh: perl: not found
Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.json?channel=plexpass

**Comment by jbeez** [comment]
Try this one I just modified, from freenas not inside of a jail:
https://raw.githubusercontent.com/jbeez/PMS_Updater/master/PMS_Updater.sh

edit your jailname up top, and i'd probably change verbose and autoupdate to 1 or feed it on the command line.
