### ISSUE TITLE
Cannot stop plex service

### ISSUE THREAD

**Issue by mattgdev69** [mstinaff/PMS_Updater#41]
Probably not directly related to the script but I cannot stop the Plex service.  The script hangs on:

Cleaning up leftover child processes
Waiting for PIDS: 39169 39168 39167 39162

The script hangs there and will not continue.  I can re-start the service but not update it.

**Comment by hunsra** [comment]
Same issue here.

**Comment by Will-i-B** [comment]
Same issue: script hangs waiting for PIDS and I can restart plex pass service but without update.  Kill command does not seem to help.  Add'l info: I have successfully run the script for prior updates.  I have plexpass if that was not already clear.  And before starting the manual update process, I updated to the latest FreeNAS OS version and updated all installed packages (ca_root_nss, wget, and perl5).  Also tried stopping jails in case the processes were contained in jails.  Unsuccessful after many attempts. Still keeps hanging.

**Comment by jbeez** [comment]
Try this one I just modified, from freenas not inside of a jail:
https://raw.githubusercontent.com/jbeez/PMS_Updater/master/PMS_Updater.sh

edit your jailname up top, and i'd probably change verbose and autoupdate to 1 or feed it on the command line.

**Comment by mattgdev69** [comment]
I could not get the updated script to work.  Attached is a screenshot.  I dropped the script in where the old script was downloaded and ran it from the FreeNAS shell (not the Jail shell).

![Screenshot from 2019-07-04 07-00-16](https://user-images.githubusercontent.com/32312016/60665303-bc35c900-9e29-11e9-9c37-eccfd1a3b648.png)

**Comment by jbeez** [comment]
I did one for inside the jail after this one too. I'm still working on improving this, but the one on my git should do it for you, https://raw.githubusercontent.com/jbeez/PMS_Updater/InjailScript/PMS_Updater.sh

This one uses python that ships with PMS instead of perl for the json decode, so it can run inside with minimal fuss. You still need wget though, I'm working on that now using fetch and cleaning it up a little. Also switching to the token auth api method instead of username/password

**Comment by mattgdev69** [comment]
Ok, thank you for working on this.  I'm still getting the same result as the first attempt.  Did I do something wrong?

![Screenshot from 2019-07-04 09-22-26](https://user-images.githubusercontent.com/32312016/60673553-9ca89b80-9e3d-11e9-8668-b58abbf2498c.png)

**Comment by jbeez** [comment]
I don't think those errors in the middle are important, it is telling you the latest version is already installed.  I'm just finishing up this plex token version if you want to try it. You already have plex installed in a jail and theres a Preferences.xml file in /Plex Media Server/ folder right? I'm finishing how it grabs your auth token from preferences file so you wont need to pass u/p anymore.

**Comment by jbeez** [comment]
Give this a shot, https://raw.githubusercontent.com/jbeez/PMS_Updater/TokenAuth/PMS_Updater.sh

Everything seems to be functioning in my testing. I also have plexpass. It still wouldn't update you though if you're on the latest version. If you updated and didn't restart plexmediaserver_plexpass to load the new files into memory you should do that. There's always the force option as well

**Comment by mattgdev69** [comment]
Success!  I re-started the service and it worked (without trying again).  I didn't really see any confirmation that the install worked or might have just missed it.  Thank you again.

![Screenshot from 2019-07-04 10-49-57](https://user-images.githubusercontent.com/32312016/60678296-a932f100-9e49-11e9-8b4e-a57b341e6a8f.png)

**Comment by mattgdev69** [comment]
I want to confirm that the "Plex Token" Version of this script works like a charm which is the last linked script above.  I was able to update to the latest version today without using credentials on the command line.  Thanks again!
