### ISSUE TITLE
Can't start plex after update

### ISSUE THREAD

**Issue by UgoCloutier** [mstinaff/PMS_Updater#46]
In the script i changed the directory from

`/usr/local/share/plexmediaserver`

to 

`/usr/pbi/plexmediaserver-amd64/share/plexmediaserver`

Because this is where my files seem to be located

Once the script has finished running, plex will no start at all.

`service plexmediaserver start` will not work either

I renamed my plexmediaserver.bak to normal and my old version is up again

Right now I'm on 1.12.2.4929 

I want to update to 1.16.5.1488

Maybe my version is too old and additional steps are required??

**Comment by ksduster** [comment]
It is not just you, I updated from 1.13.?.?? to 1.16.5.1488 (plexpass)  - using the pkg update, then pkg upgrade command and it wont run for me either now.

**Comment by jbeez** [comment]
You can try my forked version... https://github.com/jbeez/PMS_Updater  but I've not tried it on something as old as your version. Make sure you have a backup, I can't say what will happen in that old jail environment.
