### ISSUE TITLE
Can't install wget into Plex jail

### ISSUE THREAD

**Issue by afettouhi** [mstinaff/PMS_Updater#47]
I have a plex jail running on my 11.2-U6 FreeNAS server and I accidently messed up updating Plex. I am trying to update it via PMS_Updater script which I have done before but it complains that it can't find wget in the repo any more? The script also needs perl5 and cs_root_nss and these it could find. I don't understand why it is reporting this at all. wget should be installed already in this jail since I have updated before via the script.

**Comment by fahadshery** [comment]
i had the same issue ... by default its locked. You need to move the FreeBSD.conf at /usr//usr/local/etc/pkg/repos/FreeBSD.conf to a new name. then try to reinstall wget. it should work then

**Comment by afettouhi** [comment]
Yeah, I managed to figure that out via some more google searching and got wget installed. Many thanks! Closing this.
