### ISSUE TITLE
Issues updating jail containing plex plugin

### ISSUE THREAD

**Issue by afettouhi** [mstinaff/PMS_Updater#48]
I am using your script to update plex on my 11.2 Freenas server and I am having conflict issues with the openldap-client-2.4.48 package that won't install due to a conflict openldap-sasl-client-2.4.48. I don't have much experience with FreeBSD pkg package manager. So I was hoping you could give me some pointers on how to resolve this issue.

**Comment by jbeez** [comment]
Are you running the script inside of the jail or on the host system?

**Comment by afettouhi** [comment]
Inside the jail.

**Comment by jbeez** [comment]
Ok so these scripts pull down a tgz file and just unpack them, there's not really a package management function going on. 

Can you go through your process and when you're getting the error? Is this a new jail or have you been upgrading it internally for a long time? I'm trying to get a feel for maybe it being out of sync or if you've manually done things in the jail.   There are package commands to force package installs but sometimes even that fails.   OpenLDAP is a directory service which shouldn't have anything to do with plex so I definitely need more information.

**Comment by afettouhi** [comment]
It is an old jail and I have been upgrading plex inside the jail for some time now. The conflict arises when I call

`pkg update`

and then

`pkg upgrade -y`

**Comment by jbeez** [comment]
As always make a backup before you try anything, quick snapshot should do you... but, try pkg upgrade -f to force it over and see how that goes.

Honestly I would make a new plex jail in the new iocage system and migrate everything over.  Also if you go this route double check but I remember there being a gui bug for duplicate jails so you may need to create it in the cmd line. I tend to treat jails as disposable, I have a backup plex jail configured but just not on, if something goes horribly wrong I can just turn that jail on and redo my main plex jail but I haven't had to use it yet.

**Comment by afettouhi** [comment]
The jail is already an iocage jail. You mentioned earlier that OpenLDAP doesn't have anything to do with plex but it got installed into the jail when I had to install wget and perl5. This was when I first started using your script again for iocage jails.

**Comment by jbeez** [comment]
I forked this script so I didn't need to use wget and perl5 so I wouldn't have to deal with any pkg nonsense :) You can find my fork here https://github.com/jbeez/PMS_Updater
