### ISSUE TITLE
No issue - upgrade without .sh

### ISSUE THREAD

**Issue by likeahoss** [mstinaff/PMS_Updater#49]
Running FreeNAS 11.2-U6 and easily updated Plex without this .sh

Entered the Plex IOCAGE

`iocage exec plex csh`

Updated/installed 'wget and ca_root_nss'

`pkg install wget`

`pkg install ca_root_nss`

Upgraded all packages in the Plex IOCAGE

`pkg upgrade`

In this instance, the Plex IOCAGE upgraded 13 packages and installed 1.

> Updating iocage-plugins repository catalogue...
> iocage-plugins repository is up to date.
> All repositories are up to date.
> Checking for upgrades (13 candidates): 100%
> Processing candidates (13 candidates): 100%
> The following 14 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
>         aom: 1.0.0.2575
> 
> Installed packages to be UPGRADED:
>         x265: 3.1.2_2 -> 3.2
>         sdl2: 2.0.10 -> 2.0.10_1
>         plexmediaserver-plexpass: 1.16.6.1592 -> 1.18.1.1973_1
>         pciids: 20190725 -> 20191012
>         p11-kit: 0.23.16.1 -> 0.23.18.1
>         opencv-core: 3.4.1_22 -> 3.4.1_25
>         mesa-libs: 18.3.2_1 -> 18.3.2_2
>         jpeg-turbo: 2.0.2 -> 2.0.3
>         gnutls: 3.6.9 -> 3.6.10
>         ffmpeg: 4.2.1_1,1 -> 4.2.1_10,1
>         fdk-aac: 2.0.0 -> 2.0.1
>         expat: 2.2.6_1 -> 2.2.8
>         dav1d: 0.4.0 -> 0.5.1
> 
> Number of packages to be installed: 1
> Number of packages to be upgraded: 13
> 
> The process will require 141 MiB more space.
> 115 MiB to be downloaded.
> 
> Proceed with this action? [y/N]: y
> [plex] [1/14] Fetching x265-3.2.txz: 100%  964 KiB 987.3kB/s    00:01
> [plex] [2/14] Fetching sdl2-2.0.10_1.txz: 100%  864 KiB 885.0kB/s    00:01
> [plex] [3/14] Fetching plexmediaserver-plexpass-1.18.1.1973_1.txz: 100%   89 MiB  30.9MB/s    00:03
> [plex] [4/14] Fetching pciids-20191012.txz: 100%  206 KiB 211.1kB/s    00:01
> [plex] [5/14] Fetching p11-kit-0.23.18.1.txz: 100%  420 KiB 430.5kB/s    00:01
> [plex] [6/14] Fetching opencv-core-3.4.1_25.txz: 100%    2 MiB   2.2MB/s    00:01
> [plex] [7/14] Fetching mesa-libs-18.3.2_2.txz: 100%  402 KiB 412.2kB/s    00:01
> [plex] [8/14] Fetching jpeg-turbo-2.0.3.txz: 100%  343 KiB 351.3kB/s    00:01
> [plex] [9/14] Fetching gnutls-3.6.10.txz: 100%    2 MiB   2.5MB/s    00:01
> [plex] [10/14] Fetching ffmpeg-4.2.1_10,1.txz: 100%   15 MiB  16.2MB/s    00:01
> [plex] [11/14] Fetching fdk-aac-2.0.1.txz: 100%  904 KiB 925.9kB/s    00:01
> [plex] [12/14] Fetching expat-2.2.8.txz: 100%  121 KiB 124.3kB/s    00:01
> [plex] [13/14] Fetching dav1d-0.5.1.txz: 100%  362 KiB 371.2kB/s    00:01
> [plex] [14/14] Fetching aom-1.0.0.2575.txz: 100%    2 MiB   2.0MB/s    00:01
> Checking integrity... done (0 conflicting)
> [plex] [1/14] Upgrading pciids from 20190725 to 20191012...
> [plex] [1/14] Extracting pciids-20191012: 100%
> [plex] [2/14] Upgrading expat from 2.2.6_1 to 2.2.8...
> [plex] [2/14] Extracting expat-2.2.8: 100%
> [plex] [3/14] Upgrading p11-kit from 0.23.16.1 to 0.23.18.1...
> [plex] [3/14] Extracting p11-kit-0.23.18.1: 100%
> [plex] [4/14] Upgrading mesa-libs from 18.3.2_1 to 18.3.2_2...
> [plex] [4/14] Extracting mesa-libs-18.3.2_2: 100%
> [plex] [5/14] Upgrading jpeg-turbo from 2.0.2 to 2.0.3...
> [plex] [5/14] Extracting jpeg-turbo-2.0.3: 100%
> [plex] [6/14] Upgrading x265 from 3.1.2_2 to 3.2...
> [plex] [6/14] Extracting x265-3.2: 100%
> [plex] [7/14] Upgrading sdl2 from 2.0.10 to 2.0.10_1...
> [plex] [7/14] Extracting sdl2-2.0.10_1: 100%
> [plex] [8/14] Upgrading opencv-core from 3.4.1_22 to 3.4.1_25...
> [plex] [8/14] Extracting opencv-core-3.4.1_25: 100%
> [plex] [9/14] Upgrading gnutls from 3.6.9 to 3.6.10...
> [plex] [9/14] Extracting gnutls-3.6.10: 100%
> [plex] [10/14] Upgrading fdk-aac from 2.0.0 to 2.0.1...
> [plex] [10/14] Extracting fdk-aac-2.0.1: 100%
> [plex] [11/14] Upgrading dav1d from 0.4.0 to 0.5.1...
> [plex] [11/14] Extracting dav1d-0.5.1: 100%
> [plex] [12/14] Installing aom-1.0.0.2575...
> [plex] [12/14] Extracting aom-1.0.0.2575: 100%
**> [plex] [13/14] Upgrading plexmediaserver-plexpass from 1.16.6.1592 to 1.18.1.1973_1...**
> ===> Creating groups.
> Using existing group 'plex'.
> ===> Creating users
> Using existing user 'plex'.
> [plex] [13/14] Extracting plexmediaserver-plexpass-1.18.1.1973_1: 100%
> [plex] [14/14] Upgrading ffmpeg from 4.2.1_1,1 to 4.2.1_10,1...
> [plex] [14/14] Extracting ffmpeg-4.2.1_10,1: 100%

Exited the Plex IOCAGE csh and restarted Plex IOCAGE.

`exit`

`iocage restart plex`

> * Stopping plex-plexpass
>   + Running prestop OK
>   + Stopping services OK
>   + Tearing down VNET OK
>   + Removing devfs_ruleset: 5 OK
>   + Removing jail process OK
>   + Running poststop OK
> * Starting plex-plexpass
>   + Started OK
>   + Configuring VNET OK
>   + Starting services OK

Tested Plex, 10/10, would try again.

**Comment by pj-hunt** [comment]
Awsome, I'll give it a try on the next update.   Thanks

**Comment by bowenac** [comment]
Tried this, no updates for plex were found, I'm not using plex pass though. Now my jail isn't working, it will not load gui via the jail ip anymore after doing this for some reason.

**Comment by underpickled** [comment]
1.18.1.1973_1 is the latest plugin version, but not the latest Plex server version. Do you know if this will update to the latest plex version or just the latest plugin version?

**Comment by pj-hunt** [comment]
> 1.18.1.1973_1 is the latest plugin version, but not the latest Plex server version. Do you know if this will update to the latest plex version or just the latest plugin version?
> 
> Edit: decided to try myself... didn't update anything for me. Used the script and it worked.

It pulls direct from Plex, and updates to the latest Plex server.

**Comment by pj-hunt** [comment]
> 1.18.1.1973_1 is the latest plugin version, but not the latest Plex server version. Do you know if this will update to the latest plex version or just the latest plugin version?
> 
> Edit: decided to try myself... didn't update anything for me. Used the script and it worked.

AGREED; Using pkg update only updates to the latest plex pluging version.

To update to the latest plex version, use the PMS_Updater script.

**Comment by ChaosBlades** [comment]
pkg upgrade inside a FreeNAS Plugin only updates to latest FreeNAS Plugin version. Usually a month or more behind.

pkg upgrade inside a stock iocage jail only updates to the latest quarterly version. Usually months behind.

pkg upgrade inside an iocage jail using the latest repository updates to the latest version availible on freshports.org. This is usually a week or more behind.
How to change to latest repo:
`mkdir -p /usr/local/etc/pkg/repos`
`echo 'FreeBSD: {url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"}' > /usr/local/etc/pkg/repos/FreeBSD.conf`

using the script on this github page updates to the latest version publicly released by Plex from the Plex server as soon as they release it or as often as you run the script.
