### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by greigallen** [mstinaff/PMS_Updater#5]
I'm getting the following issue when running the script:

`/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Plex Media Server: not found`

I've checked that directory is there, but 'Plex Media Server' is a shortcut link?

**Comment by greigallen** [comment]
Update: I ran the script in the internal shell window in the GUI and it seemed to work.

**Comment by Arcanemagus** [comment]
Where was it failing to run? Is it still failing or not?

**Comment by vincegre** [comment]
I get exact same error here on a brand new FreeNAS install (9.3) ! Installed first Plex through plugins system of FreeNAS then copied script in root directory, created a file with my credentials and here is the error:

[root@freenas] ~# ./PMS_Updater.sh -c plex_compte
./PMS_Updater.sh: /usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Plex Media Server: not found
Done.

**Comment by Arcanemagus** [comment]
Did you do any further customization of the options at the top? The script is working perfectly in the exact same environment for me.

Here is the configuration mine has at the top:
```
URL="https://plex.tv/downloads?channel=plexpass"
DOWNLOADPATH="/tmp"
LOGPATH="/tmp"
LOGFILE="PMS_Updater.log"
PMSPARENTPATH="/usr/pbi/plexmediaserver-amd64/share"
PMSLIVEFOLDER="plexmediaserver"
PMSBAKFOLDER="plexmediaserver.bak"
PMSPATTERN="PlexMediaServer-[0-9]*.[0-9]*.[0-9]*.[0-9]*.[0-9]*-[0-9,a-f]*-freebsd-amd64.tar.bz2"
CERTFILE="/usr/local/share/certs/ca-root-nss.crt"
AUTOUPDATE=0
FORCEUPDATE=0
VERBOSE=0
REMOVE=0
LOGGING=1
```

**Comment by vincegre** [comment]
Nope changed nothing in it and it's exactly as you indicate it ! Any ideas what's wrong ? Somtehing else I can check ?

**Comment by Arcanemagus** [comment]
@vincegre is `/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Plex Media Server` a symbolic link for you as well? In my jail it isn't, but mine is a rather old jail that I have been manually updating Plex in (using this script).

**Comment by vincegre** [comment]
nope it's definitively not a link and it's strange as on previous FreeNAS instances I installed for tests, I remembered having that link but now on this instance it's not :( Not sure why.....

**Comment by Der-Paul** [comment]
I have got the same error
/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Plex Media Server: not found

brand new freenas only with plex.

the only thing in /usr/pbi/ is .pbiwrapper-amd64. nothing else

**Comment by jking1224** [comment]
vincegre: it appears you are running the script in the root of your FreeNAS server? I usually Plex is installed inside a jail on FreeNAS. you have to run the script from inside the jail, that is where Plex resides. It is correct that Plex is NOT installed in the FreeNAS root, it is installed inside a FreeNAS jail.

**Comment by vincegre** [comment]
oh oki but there is no cron server in the jails or is it ok to run it from FreeNAS cron with script at root of Plex jail ?

**Comment by jking1224** [comment]
I am not sure, but you could try to use the FreeNAS task interface to schedule a script. The script would reside in FreeNAS root contain something like:  jexec (jailname) PMS_Updater ....

**Comment by vincegre** [comment]
I found how it has to be formatted to get it workinq correctly, hope it can help others. Just add it this way in cron of FreeNAS through the webGUI:

jexec plexmediaserver_1 ./PMS_Updater.sh -u yourplexlogin -p plexpassword -a

Scrip is really fast as Plex goes away less than a minute when there is an update to do !

Thanks a lot for the script ;)

**Comment by Der-Paul** [comment]
Mayby first we have to active the shell for our plex jail?

jlst
shows the jails

jexec 1 tcsh
1 = ID of your plexmediaserver

**Comment by hansheeling** [comment]
So I am trying run the PMS_Updater.sh. I am trying to figure out where are you keeping the file itself at? I have put it on the root of my freenas server, root of the plex jail, but whenever I run the jexec plexmediaserver_1 ./PMS_Updater.sh, I get file not found? 

Thanks!

**Comment by vincegre** [comment]
Put it at root of your plex jail and it should be fine ;)

**Comment by heinrich-foto** [comment]
script placed in root directory of plex jail and a cronjob (from base system) with this command 'jexec plexmediaserver_1 ./PMS_Updater.sh -u user -p password -a' is a really great solution! thx
