### ISSUE TITLE
User error. I did not have the `ca_root_nss` package installed. Add as dependency

### ISSUE THREAD

**Issue by bullist** [mstinaff/PMS_Updater#51]
User error. I did not have the `ca_root_nss` package installed.  It's a new iocage jail in FreeNAS 11.3. It found a new update (assuming today's release) and successfully went through the update to a good end.  Thank you for the hard work you put into this script.

_Originally posted by @fvct5 in https://github.com/mstinaff/PMS_Updater/issues/50#issuecomment-576475470_

This should be added as a dependency

**Comment by fvct5** [comment]
Perfect!
