### ISSUE TITLE
Can't update plex with PMS_Updater after wget upgrade

### ISSUE THREAD

**Issue by afettouhi** [mstinaff/PMS_Updater#55]
I wanted update plex on my FReeNAS box today and I updated wget in that plex jail before that. Seems like that wget uses newer version of libc now because I get this error when running the script

´/lib/libc.so.7: version FBSD_1.6 required by /usr/local/bin/wget not found´

BTW what are the package dependencies of the PMS_Updater script?

**Comment by afettouhi** [comment]
Please ignore this issue. I got this fixed by upgrading my jail.

**Comment by kevin91270** [comment]
hello, i've got the same error how do you fix it ?

**Comment by afettouhi** [comment]
I just did a "iocage upgrade plexmediaserver" where plexmediaserver is the name of my plex jail. Then the issue went away.
