### ISSUE TITLE
Plex still says updated available

### ISSUE THREAD

**Issue by jasongi** [mstinaff/PMS_Updater#6]
Even after using the script to pull the latest plexpass version, it still says Version 0.9.12.8  An update is available. Please install manually. in the General section of settings

**Comment by tedrock** [comment]
0.9.12.8 is not the most recent version. https://forums.plex.tv/discussion/176124/plex-media-server-transcoder-preview-0-9-12-10

**Comment by Arcanemagus** [comment]
Also just a note it seems the installation can get stuck thinking there is an update. Mine has said that ever since they introduced the feature, regardless of the actual update status :unamused:.

**Comment by m4gn3to** [comment]
This issue is still unfixed.
But the update goes like a charm.
Thanks.

**Comment by bytesandbolts** [comment]
I had this same issue for over a year. I read another forum someone who had a similar issue, they got the 'update is available' message to disappear by logging out and logging back into their Plex account on the server itself.
Seems like too simple of a fix, but sure enough it fixed it for me.
