### ISSUE TITLE
-f to force a downgrade does not work

### ISSUE THREAD

**Issue by ChaosBlades** [mstinaff/PMS_Updater#61]
```
iocage exec plex ./PMS_Updater.sh -fl /PlexMediaServer-1.22.3.4523-d0ce30438-FreeBSD-amd64.tar.bz2
sed: /Plex Media Server/Preferences.xml: No such file or directory
Already running version v1.23.2.4625-a83d2d0f9
Use -f to force install /PlexMediaServer-1.22.3.4523-d0ce30438-FreeBSD-amd64.tar.bz2
```
But... I did use -f... Also tried -lf, -f -l, and -l -f. Nothing works. Just keeps asking me to use -f when I already am.

**Comment by jbeez** [comment]
Try this modification and LMK,   near the bottom of the script is
`} elif [ ! $FORCEUPDATE = 1 ] &&  [ $(verNum `basename $LOCALINSTALLFILE`) -le $(verNum $CURRENTVER) ]; then {`

try changing it to 

`} elif [ ! $FORCEUPDATE = 1 ]; then {`

not sure a version check is needed if you're trying to force override......

**Comment by 2fst4u** [comment]
> Try this modification and LMK,   near the bottom of the script is
> `} elif [ ! $FORCEUPDATE = 1 ] &&  [ $(verNum ``basename $LOCALINSTALLFILE``) -le $(verNum $CURRENTVER) ]; then {`
> 
> try changing it to 
> 
> `} elif [ ! $FORCEUPDATE = 1 ]; then {`
> 
> not sure a version check is needed if you're trying to force override......
> 

This didn't resolve the issue. I am having the same problem, downgrading doesn't seem to be possible at all.
