### ISSUE TITLE
Broken after update

### ISSUE THREAD

**Issue by niklas2233** [mstinaff/PMS_Updater#62]
Hey i just updated the script after the latest commit and it stopped working. Tried the version before and it worked flawless. dont know what the problem is but i get this error after updating the script
![Screenshot_7](https://user-images.githubusercontent.com/33903786/126039061-8438aff4-582f-4919-a774-cfb2f645b0f5.png)

**Comment by Nick-Burns4** [comment]
I am having the same issue

**Comment by MAGICCC** [comment]
Sorry I messed up the README...
Script URL as plain/raw format is https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh

**Comment by Nick-Burns4** [comment]
> Sorry I messed up the README...
> Script URL as plain/raw format is https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh

Thanks that worked!
