### ISSUE TITLE
 Plex Prefences path issue

### ISSUE THREAD

**Issue by s3540645** [mstinaff/PMS_Updater#63]
preference folder directory has wrong path.
jail version: 12.2-RELEASE-p9

PREFS="/usr/local/plex/Plex Media Server/Preferences.xml"
change to 
PREFS="/usr/local/plexdata/Plex Media Server/Preferences.xml"

**Comment by MAGICCC** [comment]
I added the path in https://github.com/mstinaff/PMS_Updater/commit/b59272d6a6c282e33db80d15a2ecdce65599b1e0
Can you try again?
Seems FreeBSD installs it to this path: https://support.plex.tv/articles/202915258-where-is-the-plex-media-server-data-directory-located/
