### ISSUE TITLE
PMS_Updater.sh: No address record

### ISSUE THREAD

**Issue by alanRfol** [mstinaff/PMS_Updater#65]
when runing 

fetch -o PMS_Updater.sh https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh

Im getting no address record

fetch: https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh: No address record

Running TrueNAS-12.0-U8

any ideas ?

**Comment by MAGICCC** [comment]
Seems you cant resolve the domain, check your DNS settings in the jail or VM you are running Plex in.
I assume `host -t A raw.githubusercontent.com` doesnt return anything

**Comment by alanRfol** [comment]
Yep NAS was playing up. Thought I had checked that first :-( 

thanks for reply
