### ISSUE TITLE
Problem Updating

### ISSUE THREAD

**Issue by rladelman771** [mstinaff/PMS_Updater#66]
Running Truenas 12-8 jail 12.2  Ran the updater

Preferences.xml not found. This will likely prevent the script from downloading the latest version of Plex. You can still manually download Plex and run PMS_Updater.sh with the -l flag.
sed: : No such file or directory
PMS_Updater.sh: /usr/local/share/plexmediaserver/Plex Media Server: not found
Using URL https://plex.tv/api/downloads/5.json
Searching https://plex.tv/api/downloads/5.json for the FreeBSD download URL .....PMS_Updater.sh: /usr/local/share/plexmediaserver/Plex Script Host: not found
Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=

**Comment by not-Boris** [comment]
Getting exactly the same issue on Jail Ver : 12.3-RELEASE-p10 | TrueNAS Release: TrueNAS-13.0-U3.1

root@<redacted>[/mnt/main/iocage/jails/plex/root]# ./PMS_Updater.sh -a
Preferences.xml not found. This will likely prevent the script from downloading the latest version of Plex. You can still manually download Plex and run PMS_Updater.sh with the -l flag.
sed: : No such file or directory
./PMS_Updater.sh: /usr/local/share/plexmediaserver/Plex Media Server: not found
Using URL https://plex.tv/api/downloads/5.json
Searching https://plex.tv/api/downloads/5.json for the FreeBSD download URL ....../PMS_Updater.sh: /usr/local/share/plexmediaserver/Plex Script Host: not found
Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=

**Comment by rladelman771** [comment]
Try entering main shell and follow these steps.  This has worked since I first posted.

jls

jexec 1 csh (replace 1 with whatever jail number you have!)

fetch -o PMS_Updater.sh https://raw.githubusercontent.com/mstinaff/PMS_Updater/master/PMS_Updater.sh

chmod 755 PMS_Updater.sh

./PMS_Updater.sh -vv -a

**Comment by not-Boris** [comment]
Brilliant, just the fix I was looking for. Thanks for the help!
