### ISSUE TITLE
Error downloading updates

### ISSUE THREAD

**Issue by dazmatic** [mstinaff/PMS_Updater#68]
`Using URL https://plex.tv/api/downloads/5.json
Searching https://plex.tv/api/downloads/5.json for the FreeBSD download URL .....Done.
Downloading https://downloads.plex.tv/plex-media-server-new/1.32.5.7349-8f4248874/freebsd/PlexMediaServer-1.32.5.7349-8f4248874-FreeBSD-amd64.tar.bz2
Error downloading https://downloads.plex.tv/plex-media-server-new/1.32.5.7349-8f4248874/freebsd/PlexMediaServer-1.32.5.7349-8f4248874-FreeBSD-amd64.tar.bz2
Command: /bin/sh /usr/local/PMS_Updater/PMS_Updater.sh -v -a failed!
Executed CronTask - /usr/local/bin/iocage exec plex /bin/sh /usr/local/PMS_Updater/PMS_Updater.sh -v -a: Removing /tmp/PlexMediaServer-1.30.2.6563-3d4dc0cce-FreeBSD-amd64.tar.bz2
Using URL https://plex.tv/api/downloads/5.json
Searching https://plex.tv/api/downloads/5.json for the FreeBSD download URL .....Done.
Downloading https://downloads.plex.tv/plex-media-server-new/1.32.5.7349-8f4248874/freebsd/PlexMediaServer-1.32.5.7349-8f4248874-FreeBSD-amd64.tar.bz2
Error downloading https://downloads.plex.tv/plex-media-server-new/1.32.5.7349-8f4248874/freebsd/PlexMediaServer-1.32.5.7349-8f4248874-FreeBSD-amd64.tar.bz2
Command: /bin/sh /usr/local/PMS_Updater/PMS_Updater.sh -v -a failed!`

Been getting this every time I try and run the script. 

Running the update manually results in the same.

Downloading the file via fetch gives an error stating that the file appear truncated

**Comment by mysticpete** [comment]
Looks like it's no longer available....

<img width="575" alt="image" src="https://github.com/mstinaff/PMS_Updater/assets/2877294/a0a40f7a-573a-4197-8698-eb835fe4753e">

**Comment by lordviceroy** [comment]
Try the steps in this gist:
https://gist.github.com/butageek/eabee7329d41040fee566dfcabbeead9

Worked perfectly fine for me just now.

**Comment by dazmatic** [comment]
Tried exactly that - download still fails. Downloading via wget works fine.

**Comment by dazmatic** [comment]
Still failing
