### ISSUE TITLE
Updated PMS not registering

### ISSUE THREAD

**Issue by silverbullettruck2001** [mstinaff/PMS_Updater#70]
When I use this script to update Plex, it completes successfully, restarts the Plex, but when it starts up it still says that an update is available even though it is now at the current release.  I have tried restarting the Plex jail and the entire TrueNAS server and nothing seems to fix it.  Any idea how to fix this?

![image](https://github.com/mstinaff/PMS_Updater/assets/26559157/65751f30-ea6d-462f-a60f-29ff9d05c285)
![Screenshot 2023-10-08 1059302](https://github.com/mstinaff/PMS_Updater/assets/26559157/7627fc4e-141b-4389-a8d4-d31276bb8a7c)

**Comment by MAGICCC** [comment]
Are you sure you use the latest script? -u and -p parameters are 9 years old

**Comment by silverbullettruck2001** [comment]
@MAGICCC thanks for the suggestion.  It had been working for so long so I didn't even think about checking for a newer version.  It now works correctly!
