### ISSUE TITLE
Script has stopped working

### ISSUE THREAD

**Issue by speedyyellow** [mstinaff/PMS_Updater#8]
I've been using this script for ages now to keep my server updated but today when I tried it I'm getting the following error:

Download Complete
Searching https://plex.tv/downloads?channel=plexpass for PlexMediaServer-[0-9]*.[0-9]*.[0-9]*.[0-9]*.[0-9]*-[0-9,a-f]*-freebsd-amd64.tar.bz2 .....Could not find a PlexMediaServer-[0-9]*.[0-9]*.[0-9]*.[0-9]*.[0-9]*-[0-9,a-f]*-freebsd-amd64.tar.bz2 download link on page https://plex.tv/downloads?channel=plexpass

I'm guessing the plex.tv download page format has changed.  Any chance of a fix?

**Comment by Arcanemagus** [comment]
Do you have PlexPass?

According to at least one other person Plex finally "fixed" it so that users without PlexPass can't access that tag, and they have implemented a fix in https://github.com/mstinaff/PMS_Updater/pull/7.

**Comment by speedyyellow** [comment]
I do have PlexPass yes.  
Oh wait a sec...  
Yeah I'm an idiot.  I've changed my password since I last updated the server and was running the script with my old plex password!

Sorry!
